"""READMEMISSING.md Generator and Parser."""

import re
from datetime import datetime
from pathlib import Path
from typing import Union

import yaml

from ..utils.logger import get_logger
from .models import GapItem, GapReport, HumanInput

logger = get_logger(__name__)


def generate_missing_md(
    gap_report: GapReport,
    topic: str,
    run_id: str,
    paper_count: int
) -> str:
    """Generate READMEMISSING.md content.
    
    Args:
        gap_report: Gap analysis report
        topic: Research topic
        run_id: Pipeline run ID
        paper_count: Number of papers reviewed
        
    Returns:
        Markdown content as string
    """
    all_items = gap_report.get_all_items()
    required_items = gap_report.get_required_items()
    
    frontmatter = {
        "status": "awaiting_human_input",
        "created": datetime.now().isoformat(),
        "run_id": run_id,
        "resume_command": f"scholarforge resume --run-id {run_id}",
        "total_items": len(all_items),
        "required_items": len(required_items)
    }
    
    lines = [
        "---",
        yaml.dump(frontmatter, default_flow_style=False).strip(),
        "---",
        "",
        "# ScholarForge — Missing Information Report",
        "",
        f"**Topic:** {topic}",
        f"**Papers Reviewed:** {paper_count}",
        f"**Run ID:** {run_id}",
        "",
        "> Fill in your responses below each item. Mark items with [x] when complete.",
        "> Items marked (REQUIRED) must be filled before the paper can be written.",
        "> Items marked (RECOMMENDED) will improve quality. Items marked (OPTIONAL) will add depth.",
        ""
    ]
    
    def add_section(title: str, items: list[GapItem], priority_label: str):
        if not items:
            return
        lines.extend([
            f"## {title} ({priority_label})",
            ""
        ])
        for item in items:
            lines.extend([
                f"- [ ] **[{item.id}]** {item.description}",
                f"  - *Priority:* {item.priority.upper()}",
            ])
            if item.default_suggestion:
                lines.append(f"  - *System default if blank:* {item.default_suggestion}")
            lines.extend([
                "  - **Your response:**",
                "  <!-- Write your response here -->",
                ""
            ])
    
    # Add sections by priority
    required_data = [i for i in gap_report.missing_data if i.priority == "required"]
    recommended_data = [i for i in gap_report.missing_data if i.priority == "recommended"]
    optional_data = [i for i in gap_report.missing_data if i.priority == "optional"]
    
    required_method = [i for i in gap_report.methodology_decisions if i.priority == "required"]
    recommended_method = [i for i in gap_report.methodology_decisions if i.priority == "recommended"]
    optional_method = [i for i in gap_report.methodology_decisions if i.priority == "optional"]
    
    add_section("Missing Data", required_data, "REQUIRED")
    add_section("Methodology Decisions", required_method, "REQUIRED")
    add_section("Missing Data", recommended_data, "RECOMMENDED")
    add_section("Methodology Decisions", recommended_method, "RECOMMENDED")
    add_section("Additional Context", gap_report.additional_context, "RECOMMENDED")
    add_section("Missing Baselines", gap_report.missing_baselines, "RECOMMENDED")
    add_section("Missing Data", optional_data, "OPTIONAL")
    add_section("Methodology Decisions", optional_method, "OPTIONAL")
    add_section("Scope Refinements", gap_report.scope_refinements, "OPTIONAL")
    
    # Footer
    lines.extend([
        "---",
        f"*Generated by ScholarForge on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}. "
        f"Edit this file, mark checkboxes [x], then run:*",
        f"```",
        f"scholarforge resume --run-id {run_id}",
        f"```"
    ])
    
    return "\n".join(lines)


class ParseError(Exception):
    """Error parsing READMEMISSING.md."""
    pass


def parse_missing_md(filepath: str) -> Union[HumanInput, ParseError]:
    """Parse a filled-in READMEMISSING.md file.
    
    Args:
        filepath: Path to READMEMISSING.md
        
    Returns:
        HumanInput if successful, ParseError otherwise
    """
    path = Path(filepath)
    if not path.exists():
        return ParseError(f"File not found: {filepath}")
    
    try:
        content = path.read_text()
    except Exception as e:
        return ParseError(f"Could not read file: {e}")
    
    # Parse frontmatter
    frontmatter_match = re.match(r'^---\s*\n(.*?)\n---\s*\n', content, re.DOTALL)
    if not frontmatter_match:
        return ParseError("Could not find YAML frontmatter")
    
    try:
        frontmatter = yaml.safe_load(frontmatter_match.group(1))
    except yaml.YAMLError as e:
        return ParseError(f"Invalid YAML frontmatter: {e}")
    
    # Extract checkboxes and responses
    checked_items: list[str] = []
    responses: dict[str, str] = {}
    
    # Pattern for checkbox items
    checkbox_pattern = r'- \[([ xX])\] \*\[([^\]]+)\]\*'
    
    # Find all checkbox items
    for match in re.finditer(checkbox_pattern, content):
        checked = match.group(1).lower() == 'x'
        item_id = match.group(2)
        
        if checked:
            checked_items.append(item_id)
        
        # Extract response - look for text after "Your response:" until next item or section
        item_start = match.end()
        next_item = re.search(r'- \[[ xX]\]', content[item_start:])
        next_section = re.search(r'## ', content[item_start:])
        
        # Find the earliest boundary
        end_pos = len(content)
        if next_item:
            end_pos = min(end_pos, item_start + next_item.start())
        if next_section:
            end_pos = min(end_pos, item_start + next_section.start())
        
        item_content = content[item_start:end_pos]
        
        # Extract response
        response_match = re.search(
            r'\*\*Your response:\*\*\s*(?:<!--.*?-->)?\s*\n(.*?)(?:\n\s*\n|\Z)',
            item_content,
            re.DOTALL
        )
        
        if response_match:
            response = response_match.group(1).strip()
            # Remove HTML comments
            response = re.sub(r'<!--.*?-->', '', response, flags=re.DOTALL).strip()
            if response and response != "Write your response here":
                responses[item_id] = response
    
    human_input = HumanInput(
        responses=responses,
        checked_items=checked_items
    )
    
    logger.info(
        f"Parsed READMEMISSING.md: {len(checked_items)} items checked, "
        f"{len(responses)} responses provided"
    )
    
    return human_input


def validate_missing_md(
    filepath: str,
    required_ids: list[str]
) -> tuple[bool, list[str]]:
    """Validate that all required items are complete.
    
    Args:
        filepath: Path to READMEMISSING.md
        required_ids: List of required item IDs
        
    Returns:
        Tuple of (is_valid, list of missing item IDs)
    """
    result = parse_missing_md(filepath)
    
    if isinstance(result, ParseError):
        return False, [str(result)]
    
    missing = []
    for item_id in required_ids:
        if not result.is_checked(item_id):
            missing.append(f"{item_id} (not checked)")
        elif not result.get_response(item_id):
            missing.append(f"{item_id} (no response)")
    
    return len(missing) == 0, missing
